credentials:
  usernames:
    admin:
      email: sanou.ezekiel226@gmail.com
      name: Sanou Ezekiel
      password: $2b$12$Rtb1tnugIpfmtBD.DTy9uOvt3ILrDDIcFVzqT8WmC9GGtl753QUM6 # To be replaced with hashed password
    Z_Benjamin:
      name: ZOUNGRANA Benjamin
      password: $2b$12$Dw1Wncyus5EXBrz28dIioOvjtP2gOBQ6.JQnjgtNjEkhDYwqizsdy # To be replaced with hashed password
    K_Armel:
      name: KABORE Armel
      password: $2b$12$Dw1Wncyus5EXBrz28dIioOvjtP2gOBQ6.JQnjgtNjEkhDYwqizsdy # To be replaced with hashed password
    
   
      

cookie:
  expiry_days: 30
  key: AAFTSS # Must be string
  name: amd_ssedev
preauthorized:
  emails:
  - kounadiad626@gmail.com